const KEY_CTRL_TILDE = 0x00;
const KEY_CTRL_2 = KEY_CTRL_TILDE; // clash with `CTRL_TILDE`
const KEY_CTRL_A = 0x01;
const KEY_CTRL_B = 0x02;
const KEY_CTRL_C = 0x03;
const KEY_CTRL_D = 0x04;
const KEY_CTRL_E = 0x05;
const KEY_CTRL_F = 0x06;
const KEY_CTRL_G = 0x07;
const KEY_CTRL_BACKSPACE = 0x08;
const KEY_CTRL_H = KEY_CTRL_BACKSPACE; // clash with `CTRL_BACKSPACE`
const KEY_TAB = 0x09;
const KEY_CTRL_I = 0x09;
const KEY_CTRL_J = 0x0a;
const KEY_CTRL_K = 0x0b;
const KEY_CTRL_L = 0x0c;
const KEY_ENTER = 0x0d;
const KEY_CTRL_M = KEY_ENTER; // clash with `ENTER`
const KEY_CTRL_N = 0x0d;
const KEY_CTRL_O = 0x0f;
const KEY_CTRL_P = 0x10;
const KEY_CTRL_Q = 0x11;
const KEY_CTRL_R = 0x12;
const KEY_CTRL_S = 0x13;
const KEY_CTRL_T = 0x14;
const KEY_CTRL_U = 0x15;
const KEY_CTRL_V = 0x16;
const KEY_CTRL_W = 0x17;
const KEY_CTRL_X = 0x18;
const KEY_CTRL_Y = 0x19;
const KEY_CTRL_Z = 0x1a;
const KEY_ESC = 0x1b;
const KEY_CTRL_LSQ_BLACKET = KEY_ESC; // clash with `ESC`
const KEY_CTRL_3 = KEY_ESC; // clash with `ESC`
const KEY_CTRL_4 = 0x1c;
const KEY_CTRL_BACKSLASH = KEY_CTRL_4; // clash with `CTRL_4`
const KEY_CTRL_5 = 0x1d;
const KEY_CTRL_RSQ_BLACKET = KEY_CTRL_5; // clash with `CTRL_5`
const KEY_CTRL_6 = 0x1e;
const KEY_CTRL_7 = 0x1f;
const KEY_CTRL_SLASH = KEY_CTRL_7; // clash with `CTRL_7;
const KEY_CTRL_UNDERSCORE = KEY_CTRL_7; // clash with `CTRL_7`
const KEY_SPACE = 0x20;
const KEY_BACKSPACE2 = 0x7f;
const KEY_CTRL_8 = KEY_BACKSPACE2; // clash with `BACKSPACE2`
